### ISSUE TITLE
scroll bug

### ISSUE THREAD

**Issue by xu6148152** [noties/Scrollable#8] opened 2015-04-19 07:56 UTC
when you are scrolling beveled, the header and the content will not scroll together

**Comment by xu6148152** [comment] 2015-04-19 08:04
may be [DragTopLayout](https://github.com/chenupt/DragTopLayout) can inspire you

**Comment by noties** [comment] 2015-05-23 12:27
Hi!
Sorry for late reply. You mean when you are scrolling header the main content is left idle?

**Comment by xu6148152** [comment] 2015-05-24 09:23
@noties   

my mean is you can scroll main content Aslant, but the header will be idle.
may be i will create a pr.I will upload the screenshot.  

![hammerheadktu84pxubinggui05242015174027](https://cloud.githubusercontent.com/assets/6329505/7787449/18cc7262-023f-11e5-816f-a4047362302f.png)

**Comment by noties** [comment] 2015-05-24 21:35
Does the header move at all? I would say that you might have missed some configuration steps, but obviously you are using the sample app... Hm, what device do you have?

**Comment by xu6148152** [comment] 2015-05-25 02:20
nexus 5.

**Comment by xu6148152** [comment] 2015-05-25 02:24
![hammerheadktu84pxubinggui05242015174027](https://cloud.githubusercontent.com/assets/6329505/7790907/e8344196-02c7-11e5-8e19-b2cc56409c8d.png)
yeah, may be you can scroll like this.

**Comment by noties** [comment] 2015-05-25 09:10
Well, screenshot didn't help... Can you please upload a video, maybe?

**Comment by xu6148152** [comment] 2015-05-25 09:52
@noties why screenshot didn't help? I marked that screenshot? Can not you understand it?

**Comment by DavidPacioianu** [comment] 2015-05-25 12:34
It is the same problem I mentioned in #6 and I didn't get it resolved even if the issue is closed. @noties you can take a look at this video from #6 
![ezgif com-gif-maker](https://cloud.githubusercontent.com/assets/10657845/7119165/9dd37ddc-e20c-11e4-9db8-e18a382a7155.gif)

**Comment by noties** [comment] 2015-06-04 08:43
@xu6148152 no, sorry, it is still very unclear...

**Comment by noties** [comment] 2015-06-04 08:44
@DavidPacioianu I reopened #6, we should continue there

**Comment by noties** [comment] 2015-06-17 10:20
@xu6148152 please see my latest comment for #6 . Maybe this was the issue

**Comment by noties** [comment] 2015-08-03 08:54
I guess we can close this now

**Closed as completed by noties** 2015-08-03 08:54 UTC
